### ISSUE TITLE
what's the rationale behind pointDistGESD?

### ISSUE THREAD

**Issue by abhishekgrewal** [sczesla/PyAstronomy#59]
> This function applies the generalized ESD test to the distances between adjacent data points, which are then requires to be distributed approximately normally.

Does that mean pointDistGESD is relaxes the requirement that data needs to be normally distributed? and it can be applied on a non-normal distribution? If yes, why?

**Comment by sczesla** [comment]
Hi there, yes and no. No, because it is the very same test. Yes, because it is applied to modified data. In particular, the differences between consecutive data points are used (x_(i+1) - x_i, differencing in time series parlance), which can help to stabilize the mean of the data by removing trends and other "slow" variation. Cheers
