### ISSUE TITLE
Add SWEET-Cat to "resource based helpers"

### ISSUE THREAD

**Issue by DanielAndreasen** [sczesla/PyAstronomy#6]
Hi Stefan,

Our group in Porto are continously updating a catalogue with parameters of stars with exoplanets. It can be found here: https://www.astro.up.pt/resources/sweet-cat/

We think it could be a nice addition to PyAstronomy along the lines with exoplanet.eu and exoplanet.org. What do you think?

I can help with the development.

Cheers,
Daniel

**Comment by sczesla** [comment]
Hi Daniel, 

I think it is a great idea to add sweet-cat.
Especially because it is continously
updated by your group. I have been
thinking about unifying the access to
the available data bases for some
time. Currently I am on holidays, but I
will surely get back to you as soon as I am back
to business.

Looking forward to implementing that
with you. 

Stefan

Am 7. Mai 2015 19:32:46 MESZ, schrieb Daniel Thaagaard Andreasen <notifications@github.com>:
>Hi Stefan,
>
>Our group in Porto are continously updating a catalogue with parameters
>of stars with exoplanets. It can be found here:
>https://www.astro.up.pt/resources/sweet-cat/
>
>We think it could be a nice addition to PyAstronomy along the lines
>with exoplanet.eu and exoplanet.org. What do you think?
>
>I can help with the development.
>
>Cheers,
>Daniel
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/sczesla/PyAstronomy/issues/6

--
Dr. Stefan Czesla
Hamburger Sternwarte

**Comment by DanielAndreasen** [comment]
Hi again Stefan,

Yesterday I went and wrote a script for doing more or less just what we want (because I was curious and had some time).
I think we can use the code as a starting point:
https://github.com/DanielAndreasen/astro_scripts/blob/master/SWEETCat.py

Daniel

**Comment by sczesla** [comment]
Hi Daniel,

thanks a lot. I had also started a something, but so far I had not come too far. I tried to incorporate
your code into the framework that was also used for the other data base access classes
(created a branch named "sweetcat"). Here is the actual code:

https://github.com/sczesla/PyAstronomy/blob/sweetcat/src/pyasl/resBased/sweet_cat.py

I also created a stub for the documentation. As far as I can see, it works so far. I wonder
whether more specific access methods should be added or other "convenience" functions.
What do you think?

Stefan

**Comment by DanielAndreasen** [comment]
It looks great. I forked it and changed a little to it. It should be visible in the pull request #7 now.
There I also describe which changes I did.

**Comment by sczesla** [comment]
Great. I merged your changes. I just adapted the table a little, because it did not
render correctly in the html docs. I also expanded the example a bit. 

BTW., would you like to be added here:  https://pyastronomy.readthedocs.org/en/latest/PyAGroup.html, appreciated as a contributor, or do you prefer not to be mentioned at all for the
time being?

**Comment by DanielAndreasen** [comment]
Ahh, I did not try to create the docs. By the way, there is a mistake in the example L37 (I also made a comment on the commit).
It should be

    info = sc.data[sc.data[star] == star]

It would be happy to be mentioned in the contributors list :)

**Comment by sczesla** [comment]
I also always struggle with the rendering of tables in restructured text...
I believe that ["star"] is correct in L37, because it refers to the "star" column. Maybe chosing
identical names was not ideal, however (:

I added you to the list of contributors. Its always cool to hear from you.

Stefan

**Comment by DanielAndreasen** [comment]
Ah yes, you are right. Probably the names confused me.
Let's close this one. Thanks for the implementation.

Daniel
